POST http://localhost:3001/api/task/5/done HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwibmFtZSI6IlRlc3QgRXIiLCJpYXQiOjE2NjkxNDcyMzd9.twCvCiv_RelHNSOt0qejfnTeVtKzscslicY1gqPKiJo
