POST http://localhost:3001/api/tasklists/13/addtask HTTP/1.1
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwibmFtZSI6IlRlc3QgRXIiLCJpYXQiOjE2NjkxMTY0MDB9.h-GV_Sqy-qVz3_0e1_wBSCJlbbqKh_roFRP74LmqK00

{
  "name": "noin kahdesti viikossa",
  "frequency": 4,
  "timeFlexibility": 1
}