name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  deployment_pipeline:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
         node-version: '16'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      
